[features]
seeds = false
skip-lint = false
[programs.localnet]
dpl = "6NumYGQrACaBTDiNwHyvmWihxejgGHDMJrEQYD7sTBN9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/anish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
