[features]
seeds = false
skip-lint = false
[programs.devnet]
dpl = "3qUwvcPVu8LLbjgZmNeMkfkTbVhXWoLmuwiJ3XHscawC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/sahilpabale/wallets/dpl/DPLHJZ1qRei383WVnbR4Q4d98UwQvVGW92Rv8iPz1yei.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
